import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fbf9f5",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#4c4636",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f0ed",
        "outline": "#7e7764",
        "outline-variant": "#cfc6b0",
        "surface-tint": "#715c00",
        "primary": "#715c00",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffe17a",
        "primary-fixed-dim": "#e4c451",
        "on-primary-fixed": "#231b00",
        "on-primary-fixed-variant": "#554500",
        "primary-container": "#f4d35e",
        "on-primary-container": "#6e5a00",
        "inverse-primary": "#e4c451",
        "secondary": "#94492c",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdbcf",
        "secondary-fixed-dim": "#ffb59b",
        "on-secondary-fixed": "#380d00",
        "on-secondary-fixed-variant": "#763217",
        "secondary-container": "#fe9d7a",
        "on-secondary-container": "#773318",
        "tertiary": "#486459",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#cae9db",
        "tertiary-fixed-dim": "#afcdc0",
        "on-tertiary-fixed": "#042018",
        "on-tertiary-fixed-variant": "#314c42",
        "tertiary-container": "#bddcce",
        "on-tertiary-container": "#466257",
        "background": "#fbf9f5",
        "on-background": "#1b1c1a",
        "surface-variant": "#e4e2de",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a"
      }
    },
  },
  plugins: [],
};
export default config;
